export default function Home() {
  return (
    <div style={{ minHeight: '100vh', background: '#fff', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '32px' }}>
      <h1 style={{ fontSize: '3rem', fontWeight: 'bold', marginBottom: '2rem', letterSpacing: '-1px' }}>AITwinBot</h1>
      <div style={{ maxWidth: 600, textAlign: 'center', fontSize: '1.15rem', marginBottom: '2.5rem', color: '#222', lineHeight: 1.7, fontWeight: 500 }}>
        <b>About this Study</b><br /><br />
        This survey explores how generative AI, like ChatGPT, can create your digital &quot;AITwinBot&quot; — a virtual avatar reflecting your personality, values, and identity.<br /><br />
        <b>What to expect:</b><br />
        • 10–15 min: Answer questions about your demographics, values, and lifestyle.<br />
        • 20–25 min: Review and assess essays generated by your AITwinBot.<br /><br />
        <b>Important:</b><br />
        • Please participate in a quiet place and use a computer.<br />
        • Attention-check questions are included; answer carefully for quality and compensation eligibility.<br />
        • If you understand and agree, press &quot;YES&quot; to continue.
      </div>
      <button style={{ background: '#000', color: '#fff', border: 'none', borderRadius: '12px', padding: '20px 48px', fontSize: '1.5rem', fontWeight: 'bold', cursor: 'pointer', marginBottom: '1.5rem' }}>
        Start Survey
      </button>
    </div>
  );
} 